name: nu_design_system
description: "The Design System packages for NU test project"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  nu_assets:
    path: ../nu_assets

dev_dependencies:
  network_image_mock: ^2.1.1